#!/usr/bin/env bash

# Android environment variables
# https://facebook.github.io/react-native/docs/getting-started.html#3-configure-the-android-home-environment-variable
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
